### ISSUE TITLE
Redis -> firebase ?

### ISSUE THREAD

**Issue by jybaek** [withinnovation/livemsg#13]
What do you think about putting a *firebase* in place of the *redis*? It is likely that the *DB* and later statistics of users will be analyzed.

I will pay for the account. :p

**Comment by jybaek** [comment]
1. Can focus on `vue.js`
   - `Node.js` and `redis` are no longer needed.

2. We need the power of `Firebase`
   - Logs, statistics, certifications, etc.
   - I can draw many pictures.

3. Why do not we try global service?
   - `redis` is not suitable for big service. Unless it is for queuing purposes.
   - Many people will use our servers instead of locally.

how about ?

**Comment by MartinYounghoonKim** [comment]
Great !
