### ISSUE TITLE
트랙별로 질문을 모아보는 기능

### ISSUE THREAD

**Issue by yujineeee** [withinnovation/livemsg#14]
어떤 발표 내용에 대한 질문인지 구분하기가 어려워 트랙별로 질문이 모아져있으면 좋을 것 같습니다.

**Comment by yujineeee** [comment]
이미 있네용.. ㅎㅎ

**Comment by MartinYounghoonKim** [comment]
@yujineeee  
관심 가져주셔서 감사합니다 
혹시나 보시고 부족한 부분이 있으면 언제든지 이슈로 남겨주시면 개선하도록 하겠습니다.

**Comment by jybaek** [comment]
@yujineeee  #4 파이어베이스 연동해서 하려고 하는데 같이 해보시겠어요? :-)
