### ISSUE TITLE
파이어베이스 연동

### ISSUE THREAD

**Issue by jybaek** [withinnovation/livemsg#16]
## API 서버와 Redis 를 대신해서 파이어베이스를 연동하도록 한다

   - Redis 에서 처리하던 데이터 적재를 `firestore` 를 통해 제공한다
   - 향후 로그인 등 인증이 필요하면 파이어베이스에 `Authentication` 를 사용하도록 한다

**Comment by MartinYounghoonKim** [comment]
@jybaek 님이 작업해주신 파이어베이스 연동 소스 반영 후 디렉토리 되었습니다.
