### ISSUE TITLE
디렉터리 정리

### ISSUE THREAD

**Issue by jybaek** [withinnovation/livemsg#18]
#16 이 처리되면 현재 `client`, `server` 로 나뉘어져 있는 디렉터리가 무의미하다. 또한 `server` 쪽은 필요 없어지므로 삭제처리 되는게 맞다.

  - `server` 디렉터리 삭제
  - `client` 디렉터리를 홈으로 변경

그에따라 `README.md` 도 수정되어야 한다.

**Comment by MartinYounghoonKim** [comment]
해당 내용 작업해서 Pull requests 날렸습니다.
